WebCW/Models/Ann.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebCW.Models
{
    public class Ann
    {
        public int id { get; set; }

        public string description { get; set; }

        public bool isSeen { get; set;}

        public virtual ApplicationUser User { get; set; }
    }
}

WebCW/Controllers/AnnsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebCW.Models;
using Microsoft.AspNet.Identity; 

namespace WebCW.Controllers
{
    public class AnnsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Anns
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult BuildAnnsTable()
        {
           
            return PartialView("_AnnTable",db.Announcements.ToList());
        }

        // GET: Anns/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ann ann = db.Announcements.Find(id);
            if (ann == null)
            {
                return HttpNotFound();
            }
            return View(ann);
        }

        // GET: Anns/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Anns/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "id,description,isSeen")] Ann ann)
        {
            if (ModelState.IsValid)
            {
                string currentUserId = User.Identity.GetUserId();
                ApplicationUser currentUser = db.Users.FirstOrDefault(
                    x => x.Id == currentUserId);
                ann.User = currentUser;
                db.Announcements.Add(ann);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(ann);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult AJAXCreate([Bind(Include = "id,description")] Ann ann)
        {
            if (ModelState.IsValid)
            {
                string currentUserId = User.Identity.GetUserId();
                ApplicationUser currentUser = db.Users.FirstOrDefault(
                    x => x.Id == currentUserId);
                ann.User = currentUser;
                ann.isSeen = false;
                db.Announcements.Add(ann);
                db.SaveChanges();
                
            }

            return PartialView("_AnnTable", db.Announcements.ToList());
        }





        // GET: Anns/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ann ann = db.Announcements.Find(id);

            if (ann == null)
            {
                return HttpNotFound();
            }
            string currentUserId = User.Identity.GetUserId();
            ApplicationUser CurrentUser = db.Users.FirstOrDefault
                (x => x.Id == currentUserId);

            if (ann.User != CurrentUser)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(ann);
        }

        // POST: Anns/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,description,isSeen")] Ann ann)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ann).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ann);
        }

        [HttpPost]
        [Authorize]

        public ActionResult AJAXEdit(int? id, bool value)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ann ann = db.Announcements.Find(id);
            if (ann == null)
            {
                return HttpNotFound();
            }
            else
            {
                ann.isSeen = value;
                db.Entry(ann).State = EntityState.Modified;
                db.SaveChanges();
                return PartialView("_AnnTable", db.Announcements.ToList());
            }
          
        }



        // GET: Anns/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ann ann = db.Announcements.Find(id);
            if (ann == null)
            {
                return HttpNotFound();
            }
            return View(ann);
        }

        // POST: Anns/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Ann ann = db.Announcements.Find(id);
            db.Announcements.Remove(ann);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebCW/Views/Anns/Create.cshtml
@model WebCW.Models.Ann

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Ann</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.isSeen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.isSeen)
                    @Html.ValidationMessageFor(model => model.isSeen, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebCW/Views/Anns/Delete.cshtml
@model WebCW.Models.Ann

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ann</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isSeen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isSeen)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebCW/Views/Anns/Details.cshtml
@model WebCW.Models.Ann

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Ann</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isSeen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isSeen)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebCW/Views/Anns/Edit.cshtml
@model WebCW.Models.Ann

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Ann</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.isSeen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.isSeen)
                    @Html.ValidationMessageFor(model => model.isSeen, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebCW/Views/Anns/Index.cshtml
@model WebCW.Models.Ann

@{
    ViewBag.Title = "Index";
}



<div id="tableDiv"></div>
<div id="AnnouncementCreateForm">
    @using (Ajax.BeginForm("AJAXCreate", "Anns", new AjaxOptions
    {
        InsertionMode = InsertionMode.Replace,
        HttpMethod = "POST",
        UpdateTargetId = "tableDiv"
    }))
    {
        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

    }

</div>

@section Scripts {
   <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
   <script src="~/Scripts/BuildTable.js"></script> 
    
    @Scripts.Render("~/bundles/jqueryval") 
}

WebCW/Views/Anns/_AnnTable.cshtml
@model IEnumerable<WebCW.Models.Ann>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.isSeen)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User)
        </th>
        
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.isSeen, new { id = item.id})
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.Email)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                @Html.ActionLink("Details", "Details", new { id = item.id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.id })
            </td>
        </tr>
    }

</table>

<script src="=~Scripts/addcheckboxlistener.js"></script>